CREATE TABLE IF NOT EXISTS BOOK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    publisher_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS PUBLISHER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO PUBLISHER (name) VALUES ('Flamingo Classics');
